nav:
    - Introduction: index.md
#{{ 这是kernel的两个主要任务   
    - Interaction-with-hardware: Interaction-with-hardware
    - Multitasking: Multitasking
# 这是kernel的两个主要任务 }}
    - Kernel-Task-model: Kernel-Task-model 
    - User-system: User-system
    - Memory-management: Memory-management
    - Read-code: Read-code

    - Kernel-data-structure: Kernel-data-structure
    - Debug: Debug
    - Limit: Limit

    - Linux-startup-process: Linux-startup-process

    
    
    
backup:
    - How-OS-run-01-OS-kernel-is-event-driven: How-OS-run-01-OS-kernel-is-event-driven.md
    - How-OS-run-02-kernel-control-path-and-reentrant-kernel: How-OS-run-02-kernel-control-path-and-reentrant-kernel.md
    - How-OS-run-03-Control-path-&-Context-&-Context-switch: How-OS-run-03-Control-path-&-Context-&-Context-switch.md
    - How-OS-run-04-multitask: How-OS-run-04-multitask.md
    - How-OS-run-05-process-model: How-OS-run-05-process-model.md
    - How-OS-run-06-process-address-space: How-OS-run-06-process-address-space.md
    - How-OS-run-07-thread: How-OS-run-07-thread.md
    - How-OS-run-08-Entry-point-of-kernel: How-OS-run-08-Entry-point-of-kernel.md
    - VS-process-VS-thread-VS-lightweight-process: VS-process-VS-thread-VS-lightweight-process.md