nav:
    - Introduction: index.md
    - 5.5-Stopping-and-Starting-Multi-thread-Programs: 5.5-Stopping-and-Starting-Multi-thread-Programs
    - Breakpoint-conditional-expressions: Breakpoint-conditional-expressions.md
    - gdb-watch: gdb-watch
    