nav:
    - Introduction: index.md
    
    - course-dartmouth-CS60-Computer-Networks: course-dartmouth-CS60-Computer-Networks
    
    - Book-Beej's-Guide-to-Network-Programming: Book-Beej's-Guide-to-Network-Programming
    
    - Linux-TCP-impl: Linux-TCP-impl
    
    - Socket: Socket
    
    - Port: Port
    
    - man-2-bind: man-2-bind
    
    - man-2-listen: man-2-listen
    
    - man-3-getaddrinfo: man-3-getaddrinfo
    
    - Close-socket: Close-socket
    
    - Reconnect: Reconnect.md
    
    - man-2-sendfile: man-2-sendfile
    
    - Broadcast-multicast: Broadcast-multicast
    
    - TCP-Wrappers: TCP-Wrappers
