nav:
    - Introduction: index.md
    - gdb-primer: gdb-primer    
    - Design-of-gdb: Design-of-gdb
    - GDB-CRUD-data: GDB-CRUD-data
    - Point-in-GDB: Point-in-GDB.md
    - Function: Function
    - Automate: Automate
    - Args: Args
    - Debug-process: Debug-process    
    - Debug-shared-library: Debug-shared-library
    - Debug-HS-middleware: Debug-HS-middleware
    - Debug-multi-thread: Debug-multi-thread
    - Debug-assembly: Debug-assembly
    - Debug-Python: Debug-Python
    - 保存输出到文件: 保存输出到文件
    