nav:
    - Unix-filesystem: Unix-filesystem.md
    - man-7-file-hierarchy: man-7-file-hierarchy.md
    - Inode: Inode.md
    - man-2-stat: man-2-stat.md
    - File-type: File-type.md
    - Tools: Tools