nav:
    - Organization-of-process: Organization-of-process
    - Process-state: Process-state
    - Create-process: Create-process 
    - Wait-child-process: Wait-child-process
    - Process-termination: Process-termination
    - Block-process: Block-process
    - Daemon: Daemon
    - IPC: IPC