nav:
    - Organization-of-process: Organization-of-process
    - Process-state: Process-state
    - Create-process: Create-process 
    - Process-termination: Process-termination

    - Block-process: Block-process

    - Daemon: Daemon
    
    - IPC: IPC
    
    - Linux-implementation: Linux-implementation
