nav:
    - Introduction: index.md
    - 4.1-The-Role-of-Interrupt-Signals: 4.1-The-Role-of-Interrupt-Signals
    - 4.2-Interrupts-and-Exceptions: 4.2-Interrupts-and-Exceptions
    - 4.3-Nested-Execution-of-Exception-and-Interrupt-Handlers: 4.3-Nested-Execution-of-Exception-and-Interrupt-Handlers
    
    - 4.5-Exception-Handling: 4.5-Exception-Handling
    
    