nav:
    # multitask是OS的关键特性，本章就是沿着它来进行展开
    - Introduction: index.md
    # 综述process model 
    - Process-model: Process-model
    # Sched
    - Sched: Sched

    
backup:
    - Process-model-run-time-environment: 01-Process-model-run-time-environment.md
    - Process-model-memory-model: 01-Process-model-memory-model.md
    - Process-model-life-cycle: 01-Process-model-life-cycle.md
    - Subroutine: Subroutine
    - ABI: ABI
    - Control-path-&-Context-&-Context-switch: Control-path-&-Context-&-Context-switch.md
    - Linux-OS-implementation-of-process-model-01: 03-01-Linux-OS-implementation-of-process-model.md
    - Linux-OS-implementation-of-process-model-02: 03-02-Linux-OS-implementation-of-process-model.md
    - Linux-OS-implementation-of-process-model-03: 03-03-Linux-OS-implementation-of-process-model.md
    - Thread: 04-Thread.md
    - Sched: Sched
    
    