nav:
    # multitask是OS的关键特性，本章就是沿着它来进行展开
    - Introduction: index.md
    # 综述process model 
    - Process-model: Process-model
    - Process-memory: Process-memory
    - Process-file: Process-file
    # Sched
    - Scheduler: Scheduler

    - System-call-summary: System-call-summary
    - Process: Process
    - Thread: Thread
    # 对它进行专门的描述


    
    - Credential: Credential    
    - Tools: Tools
    - proc-filesystem: proc-filesystem
    
    