nav:
    # multitask是OS的关键特性，本章就是沿着它来进行展开
    - Introduction: index.md
    # 综述process model 
    - Process-model: Process-model
    # Sched
    - Sched: Sched

    
    - Process: Process
    - Thread: Thread
    # 对它进行专门的描述
    - Implementation-Clone: Implementation-Clone
    - Sched: Sched
    - Capabilities: Capabilities
    - Credential: Credential    
    - Tools: Tools
    
    