nav:
    - Introduction: index.md
    - linuxjournal-Zero-Copy-I-User-Mode-Perspective: linuxjournal-Zero-Copy-I-User-Mode-Perspective
    - developpaper-Analysis-of-zero-copy-technology-in-Linux: developpaper-Analysis-of-zero-copy-technology-in-Linux
    - joshbialkowski-Linux-Zero-Copy: joshbialkowski-Linux-Zero-Copy
    - splice系列-zero-copy-system-call: splice系列-zero-copy-system-call
    - Zero-copy-VS-COW-copy-on-write: Zero-copy-VS-COW-copy-on-write