nav:
    - Unix-filesystem: Unix-filesystem
    - Linux-virtual-file-system: Linux-virtual-file-system
    - man-7-file-hierarchy: man-7-file-hierarchy
    - Inode: Inode
    - man-2-stat: man-2-stat
    - File-type: File-type
    - Tools: Tools