nav:
    - Introduction: index.md
    - Preemptive-multitasking: Preemptive-multitasking
    - Cooperative-multitasking: Cooperative-multitasking
    - man-7-sched: man-7-sched.md
    - Context-switch: Context-switch.md
    - Unix-Scheduler-and-Dispatcher: Unix-Scheduler-and-Dispatcher.md
    - Processor-affinity: Processor-affinity
    
    