nav:
    - Introduction: index.md
    - wikipedia-Signal(IPC): wikipedia-Signal(IPC)
    - man-7-signal: man-7-signal
    - Unix-Termination-Signals: Unix-Termination-Signals
    - Signal-handler: Signal-handler.md
    