nav:
    - Introduction: index.md
#{{ 这是kernel的两个主要任务   
    - Interaction-with-hardware: Interaction-with-hardware
    - Multitasking: Multitasking.md
# 这是kernel的两个主要任务 }}
    - User-system: User-system
    - Resource-management: Resource-management
    

  


    

    
