nav:
    - Introduction: index.md
    - 3.1-Processes-and-Lightweight-Processes-and-Threads: 3.1-Processes-and-Lightweight-Processes-and-Threads
    - 3.2-Process-Descriptor: 3.2-Process-Descriptor
    - 3.2.1-Process-State: 3.2.1-Process-State
    - 3.2.2-Identifying-a-Process: 3.2.2-Identifying-a-Process
    - 3.2.2.1-Process-descriptors-handling: 3.2.2.1-Process-descriptors-handling
    - 3.2.2.2-Identifying-the-current-process: 3.2.2.2-Identifying-the-current-process
    - 3.2.2.3-Doubly-linked-lists: 3.2.2.3-Doubly-linked-lists
    - 3.2.2.4-The-process-list: 3.2.2.4-The-process-list
    - 3.2.2.5-The-lists-of-TASK_RUNNING-processes: 3.2.2.5-The-lists-of-TASK_RUNNING-processes
    - 3.2.3-Relationships-Among-Processes: 3.2.3-Relationships-Among-Processes
    - 3.2.4-How-Processes-Are-Organized: 3.2.4-How-Processes-Are-Organized
    - 3.2.5-Process-Resource-Limits: 3.2.5-Process-Resource-Limits
    - 3.3-Process-Switch: 3.3-Process-Switch
    - 3.4-Creating-Processes: 3.4-Creating-Processes
    - 3.4.2-Kernel-Threads: 3.4.2-Kernel-Threads
    