nav:
    - Introduction: index.md
    - What-is-multiplexing: What-is-multiplexing
    - What-is-IO-multiplexing: What-is-IO-multiplexing
    - IO-events: IO-events
    - Multiplex-on-file-descriptor: Multiplex-on-file-descriptor
    - System-call-summary: System-call-summary
    - select: select
    - poll: poll
    - epoll: epoll
    - select-VS-poll-VS-epoll: select-VS-poll-VS-epoll
