nav:
    - Introduction: index.md
    - What-is-multiplexing: What-is-multiplexing
    - What-is-IO-multiplexing: What-is-IO-multiplexing
    - Multiplex-on-file-descriptor: Multiplex-on-file-descriptor
    - select: select
    - poll: poll
    - epoll: epoll
    - Summary: Summary    
