nav:
    - Introduction: index.md
    - Design-of-gdb: Design-of-gdb
    - Guide-to-controlling-process: Guide-to-controlling-process.md
    - Guide-to-examining-data: Guide-to-examining-data.md
    - Point-in-GDB: Point-in-GDB.md
    - Function: Function
    - Automate: Automate
    - gdb-primer: gdb-primer
    - Args: Args
    - Debug-shared-library: Debug-shared-library
    - Debug-HS-middleware: Debug-HS-middleware
    - Debug-multi-thread: Debug-multi-thread
    - Debug-assembly: Debug-assembly.md    