nav:
    - Introduction: index.md
    - Why-system-call-slow: Why-system-call-slow
    - Classification: Classification
    - Interrupted-system-call: Interrupted-system-call
    - Zero-copy: Zero-copy
    - p-system-call: p-system-call
    - Linux-system-call-table: Linux-system-call-table
    