nav:
    - Introduction: index.md
    - Operating-system-kernel: Operating-system-kernel
    - Guide: Guide    
    - Book-Understanding-the-Linux-Kernel: Book-Understanding-the-Linux-Kernel    

    - 主要功能: 主要功能
    - System-call: System-call
    - Read-the-code: Read-the-code
    - Debug-kernel: Debug-kernel