nav:
    - Introduction: index.md
    - Operating-system-kernel: Operating-system-kernel
    - Book-Understanding-the-Linux-Kernel: Book-Understanding-the-Linux-Kernel    
    - Kernel-architecture: Kernel-architecture
    - 主要功能: 主要功能
    - Guide: Guide
