nav:
    - Introduction: index.md
    - Kernel(operating system): Kernel(operating system)
    - Architecture: Architecture.md
    - Guide: Guide
    - Book-Understanding-the-Linux-Kernel: Book-Understanding-the-Linux-Kernel