#!/bin/bash
USAGEMETHOD="Usage: `basename $0` corename"

case "$1" in
"" ) echo $USAGEMETHOD; exit $E_WRONGARGS;;
* ) CORE_NAME=$1;;
esac
echo file:$CORE_NAME

HSSERVER=$(echo q|gdb --quiet -c $CORE_NAME 2>&1|grep "Core was generated by")
CONFIG_FILE_NAME=$(echo $HSSERVER|grep " -f "| awk -F '-f' '{printf("%s", $NF);}' | awk '{printf("%s", $1);}')
HSSERVER=$(echo $HSSERVER | awk '{printf("%s", $5);}'| awk -F '\047' '{printf("%s", $1);}' | awk -F ':' '{printf("%s", $1);}')
HSSERVER=${HSSERVER#*'`'}
echo exe:$HSSERVER
echo config:$CONFIG_FILE_NAME

HSAPPNAME=
HSSERVER_LOG=

if [ ! -f "$CONFIG_FILE_NAME" ]
then
  CONFIG_FILE_NAME=
else
HSAPPNAME=$(cat $CONFIG_FILE_NAME|grep "<application name="| awk -F '"' '{printf("%s", $2);}')
HSSERVER_LOG=log/*$HSAPPNAME*
fi

CORE_NAME_RESULT=$CORE_NAME.result
CORE_NAME_LOG=$CORE_NAME.log

DSTPATH=libs$(date +%Y%02m%02d)

echo "set pagination off" > $CORE_NAME_LOG
echo "i sharedlibrary" >> $CORE_NAME_LOG
echo "q" >> $CORE_NAME_LOG

gdb $HSSERVER $CORE_NAME < $CORE_NAME_LOG 2>&1 > $CORE_NAME_RESULT

echo "#!/bin/bash" > $CORE_NAME_LOG
echo "rm -rf" $DSTPATH >> $CORE_NAME_LOG
echo "mkdir " $DSTPATH >> $CORE_NAME_LOG
echo "mkdir " $DSTPATH"/bin" >> $CORE_NAME_LOG

BINCOUNT=$(which $HSSERVER 2>/dev/null)
if [ -n "$BINCOUNT" ]
then
echo "cp " $BINCOUNT $DSTPATH"/bin" >> $CORE_NAME_LOG
else
echo "ERROR" $HSSERVER "is not exist, please use the hundsun user or other users to perform getcore.sh"
exit
fi;

echo path:$DSTPATH

LIBPATH=$(cat $CORE_NAME_RESULT |grep " Yes ")
case "$LIBPATH" in
"" ) LIBPATH=$(cat $CORE_NAME_RESULT |grep " No ");;
esac

case "$LIBPATH" in
"" ) echo "corefile:"$CORE_NAME "do not find the business library list, please use the hundsun user or other users to perform getcore.sh"; exit;;
esac

cat $CORE_NAME_RESULT |grep " Yes "|awk -v CORE_NAME_LOG=$CORE_NAME_LOG -v DSTPATH=$DSTPATH -F' ' '{system("echo cp --parents " $NF " " DSTPATH " >> " CORE_NAME_LOG);system("echo chmod -R +w " DSTPATH ">>" CORE_NAME_LOG);}'
cat $CORE_NAME_RESULT |grep " No "|awk -v CORE_NAME_LOG=$CORE_NAME_LOG -v DSTPATH=$DSTPATH -F' ' '{system("echo cp --parents " $NF " " DSTPATH " >> " CORE_NAME_LOG);system("echo chmod -R +w " DSTPATH ">>" CORE_NAME_LOG);}'

echo "mv " $CORE_NAME_LOG $DSTPATH >> $CORE_NAME_LOG
echo "mv " $CORE_NAME_RESULT $DSTPATH >> $CORE_NAME_LOG
echo "tar -zcvf" $CORE_NAME".tar.gz" $DSTPATH $CORE_NAME $HSSERVER_LOG $CONFIG_FILE_NAME>> $CORE_NAME_LOG
echo "rm -rf " $DSTPATH >> $CORE_NAME_LOG
sh $CORE_NAME_LOG
