nav:
    - Chapter-1-Introduction: Chapter-1-Introduction
    - 1.1-Linux-Versus-Other-Unix-Like-Kernels: 1.1-Linux-Versus-Other-Unix-Like-Kernels
    - 1.2-Hardware-Dependency: 1.2-Hardware-Dependency
    - 1.4-Basic-Operating-System-Concepts: 1.4-Basic-Operating-System-Concepts
    - 1.6-An-Overview-of-Unix-Kernels: 1.6-An-Overview-of-Unix-Kernels
    - 1.6.1-The-Process-Kernel-Model: 1.6.1-The-Process-Kernel-Model
    - 1.6.2-Process-Implementation: 1.6.2-Process-Implementation
    - 1.6.3-Reentrant-Kernels: 1.6.3-Reentrant-Kernels
    - 1.6.4-Process-Address-Space: 1.6.4-Process-Address-Space
    - 1.6.5-Synchronization-and-Critical-Regions: 1.6.5-Synchronization-and-Critical-Regions
    - 1.6.6-Signals-and-Interprocess-Communication: 1.6.6-Signals-and-Interprocess-Communication
    - 1.6.7-Process-Management: 1.6.7-Process-Management
    - 1.6.8-Memory-Management: 1.6.8-Memory-Management
    - 1.6.9-Device-Drivers: 1.6.9-Device-Drivers
    