nav:
    - Introduction: index.md
    - Debugger: Debugger.md
    - Trap: Trap.md
    - Trace: Trace.md
    - GDB: GDB
    - Stack-trace: Stack-trace
    - trace-system-call: trace-system-call
    - Library-call-tracer: Library-call-tracer
    - Application: Application