nav:
    - Introduction: index.md
    - toptal-Separation-Anxiety-Tutorial-for-Isolating-Your-System-with-Linux-Namespaces: toptal-Separation-Anxiety-Tutorial-for-Isolating-Your-System-with-Linux-Namespaces
    - man-7-namespaces: man-7-namespaces