nav:
    - Home: index.md
    
    - Architecture-of-computing-system: Architecture-of-computing-system
    
    - Operating-system: Operating-system
    
    - Course-upenn-CSE-380-Computer-Operating-Systems: Course-upenn-CSE-380-Computer-Operating-Systems
    
    - Unix-standardization&implementation: Unix-standardization&implementation ########## 描述linux OS的标准与实现##########
    
    - Linux-Foundation: Linux-Foundation ##########Linux-Foundation定义了linux OS的方方面面##########               
    
    - Kernel: Kernel ########## 描述内核的相关知识##########             
    
    - Linux-startup-process: Linux-startup-process ########## 启动过程 ##########
    
    - System-call: System-call # 系统调用
    
    - Multitasking: Multitasking ########## 多任务 ###########

    - Programming: Programming ########## 描述linux OS中进行programming时的知识##########            

    - Network: Network ########## 描述网络的知识##########                 
    
    - Event-driven-concurrent-server: Event-driven-concurrent-server
    
    - Security: Security # 安全
    
    - 运维管理: 运维管理
    
    - Shell&tool: Shell&tool # 描述在linux OS中进行programming时，需要使用的一些工具

    - Book: Book
    
    - Ubuntu: Ubuntu
    
    - macOS: macOS
    
    - docker: docker
    