nav:
    - Introduction: index.md
    - 6.1-Clock-and-Timer-Circuits: 6.1-Clock-and-Timer-Circuits
    - 6.2-The-Linux-Timekeeping-Architecture: 6.2-The-Linux-Timekeeping-Architecture
    - 6.4-Updating-System-Statistics: 6.4-Updating-System-Statistics