nav:
    - Introduction: index.md
    - Thread-control-block: Thread-control-block
    - man-7-pthreads: man-7-pthreads
    - man-7-attributes: man-7-attributes
    
    - Synchronization: Synchronization
    - Cancel-thread: Cancel-thread