nav:
    - Introduction: index.md
    - Thread-control-block: Thread-control-block
    - man-7-pthreads: man-7-pthreads
    - man-7-attributes: man-7-attributes
    

    - Create-thread: Create-thread
    - Cancel-thread: Cancel-thread
    - Join-thread: Join-thread
    - Detach-thread: Detach-thread
    - Synchronization: Synchronization    