nav:
    - Introduction: index.md
    - Preemptive-multitasking: Preemptive-multitasking
    - Cooperative-multitasking: Cooperative-multitasking
    - Context-switch: Context-switch

    - Linux-implementation: Linux-implementation
    - Multicore-scheduler-process: Multicore-scheduler-process
    